import {AppProvider} from "@/components/AppContext";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "../components/layout/Header";
import {Toaster} from "react-hot-toast";
import Image from 'next/image';
import Link from "next/link";




const roboto = Roboto({ subsets: ["latin"],weight:["400","500","700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
    <html lang="en" className="scroll-smooth">
      <body className={'${roboto.className} bg-secondary'}>
        <main className="max-w-6xl mx-auto p-4">
          <AppProvider>
            <Toaster/>
            <Header />
            {children}
            <footer className="border-t p-8 text-center text-gray-200 mt-32">
              &copy; 2024 All Rights Reserved
              <div className="flex items-center space-x-2">
                <span className="text-gray-600 text-sm sm:text-base">Design and Developed By</span>
                <Link href={'https://www.linkedin.com/in/pasindu-niroshana-7a940225b/'}>
                  <Image
                   src={'/linkedin.png'} 
                   width={20} height={20} 
                   alt={'linkedin'}
                   className="w-4 h-4 sm:w-6 sm:h-6"/>
                </Link>
              </div>
            </footer>
          </AppProvider>
        </main> 
      </body>
    </html>
  );
}
